### ISSUE TITLE
cet_website_sale : Bad query

### ISSUE THREAD

**Issue by houssine78** [coopiteasy/cycle-en-terre#40]
I got this error on our test server 
ERROR cycleenterre-test-11 odoo.sql_db: bad query: b'SELECT set_limit(0.100000);'
ERROR: function set_limit(numeric) does not exist
LINE 1: SELECT set_limit(0.100000);
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

it seems to come from here https://github.com/coopiteasy/cycle-en-terre/blob/11.0/cet_website_sale/controllers/main.py#L59

**Comment by robinkeunen** [comment]
- Est-ce que le module [pgtrgm](https://www.postgresql.org/docs/9.1/pgtrgm.html) est installé en local? Sur les serveurs?
- Est-ce que tu as la bonne version de postgres en local? Sur les serveurs?

Chez moi: `PostgreSQL 11.1`, le module ne semble pas être installé par défaut:

```sql
robinkeunen@/tmp:postgres> select * from pg_available_extensions where name like '%pg%trgm%'
+---------+-------------------+---------------------+-------------------------------------------------------------------+
| name    | default_version   | installed_version   | comment                                                           |
|---------+-------------------+---------------------+-------------------------------------------------------------------|
| pg_trgm | 1.4               | <null>              | text similarity measurement and index searching based on trigrams |
+---------+-------------------+---------------------+-------------------------------------------------------------------+
SELECT 1
Time: 0.017s
```

Sur le serveur de test: `psql (9.5.14)` le module n'est pas installé
```sql
cycleenterre-test-11> select * from pg_available_extensions where name like '%pg%trgm%'
+---------+-------------------+---------------------+-------------------------------------------------------------------+
| name    |   default_version |   installed_version | comment                                                           |
|---------+-------------------+---------------------+-------------------------------------------------------------------|
| pg_trgm |               1.1 |              <null> | text similarity measurement and index searching based on trigrams |
+---------+-------------------+---------------------+-------------------------------------------------------------------+
SELECT 1
Time: 0.005s
```

Je n'ai plus accès au serveur de prod, il faudrait vérifier que ma clé publique est toujours dans `.ssh/authorized_keys`.

**Comment by robinkeunen** [comment]
ran as posgres user
```sql
create extension pg_trgm
```

**Comment by houssine78** [comment]
thanks bro !

Le lun. 14 janv. 2019 à 15:33, Robin Keunen <notifications@github.com> a
écrit :
